OxyProcess/Controllers/TemplateController.cs
namespace OxyProcess.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using Newtonsoft.Json;
    using OxyProcess.Constant;
    using OxyProcess.Data;
    using OxyProcess.Models;
    using OxyProcess.Models.FormTag;
    using OxyProcess.Models.Template;
    using OxyProcess.ViewModels.FormTag;
    using OxyProcess.ViewModels.Template;
    using AutoMapper;
    using System.Collections;

    [Authorize(Roles = "Admin")]
    public class TemplateController : Controller
    {
        #region Property  
        public readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        //private readonly IMapper _mapper;
        #endregion
        private readonly IMapper _mapper;
        public TemplateController(ApplicationDbContext context, IMapper mapper, SignInManager<ApplicationUser> s/*, IMapper mapper*/)
        {
            _context = context;
            _signInManager = s;
            _mapper = mapper;
            //_mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
          
        }


       
        //Get Templatelist By User 
        public string GetTemplatelist()
        {
            try
            {
                int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var list = _context.Template.Include(e => e.TemplateType).Where(e => e.CreatedById == userid.ToString() && e.IsDeleted == false).OrderByDescending(e => e.TemplateId).ToList();
                var json = JsonConvert.SerializeObject(list);
                return json;
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        //Change Template Activation
        [HttpPost]
        [AllowAnonymous]
        public JsonResult ChangeTemplateActivation(Template template)
        {
            try
            {
                int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);

                Template TemplateUpdate = _context.Template.FirstOrDefault(e => e.TemplateId == template.TemplateId && e.CreatedById == userid.ToString());
                TemplateUpdate.IsActive = template.IsActive;
                _context.SaveChanges();
                return Json("True");
            }

            catch (Exception ex)
            {
                return Json("False");
            }
        }

        [Route("Template/CreateTemplate")]
        [HttpGet]
        public IActionResult CreateTemplate()
        {
            int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            ViewData["Groups"] = _context.Groups.Where(e => e.CreatedById == userid.ToString()).ToList();
            ViewBag.TemplateType = new SelectList(_context.TemplateType, "TypeId", "TemplateTypeName");
            return View();
        }
        //Create new Template Post method 
        [HttpPost]
        [AllowAnonymous]
        public JsonResult CreateEditTemplate(TemplateViewModel model)
        {
            try
            {

                if (_signInManager.IsSignedIn(User))
                {
                    int userId = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                    var user = _context.Users.FirstOrDefault(e => e.Id == userId);

                    if (model.TemplateName == "" || model.TemplateCode == "" || model.Groups == "")
                    {
                        return Json(new { message = "Please enter filds Data." });
                    }

                    if (model.TemplateId > 0)
                    {

                        Template template = _context.Template.FirstOrDefault(e => e.TemplateId == model.TemplateId);
                        if (template.TemplateName.ToLower().Trim() != model.TemplateName.ToLower().Trim())
                        {

                            var templateName = _context.Template.Count(e => e.TemplateName.ToLower() == model.TemplateName.ToLower() && e.CreatedById == userId.ToString());
                            if (templateName != 0)
                            {
                                ViewData["TemplateNameAvailable"] = "true";
                                return Json(new { message = "Template name is already exist." });
                            }
                        }

                        //if template is reportcard remove add custome titel field from db
                        if (model.TemplateTypeId == 1)
                        {
                            var dbcode = JsonConvert.DeserializeObject<List<object>>(template.TemplateCode);
                            
                            var modelcode = JsonConvert.DeserializeObject<List<object>>(model.TemplateCode);
                            //re-add db code titel to current model code 
                            modelcode.Insert(0,dbcode[0]);
                            model.TemplateCode = JsonConvert.SerializeObject(modelcode);

                        }

                        template.TemplateCode = model.TemplateCode;
                        template.TemplateName = model.TemplateName.Trim();
                        template.TemplateTypeId = model.TemplateTypeId;
                        template.Groups = model.Groups;
                        template.CreatedDate = template.CreatedDate;
                        template.CreatedById = userId.ToString();
                        template.IsActive = template.IsActive;
                        template.IsDeleted = false;
                        template.CompanyId = (int)user.CompanyId;
                        _context.SaveChanges();
                        //return Json(new { message = "Sucess" });
                        var templateuseintag = _context.TaginsideTemplates.Where(e => e.OrignalTemplateId == model.TemplateId);

                        List<TemplateFields> templateFields = new List<TemplateFields>();

                        foreach (var single in templateuseintag)
                        {
                            var templateuseintag2 = _context.TemplateFields.Where(e => e.TemplateuniqueId == single.TemplateuniqueId);

                            var templateField = JsonConvert.DeserializeObject<List<TemplateFieldsViewModel>>(model.TemplateCode);


                            foreach (var tField in templateField)
                            {

                                if (templateuseintag2.Count(x => x.name == tField.name && x.type == tField.type) == 0)
                                {

                                    var output = _mapper.Map<TemplateFields>(tField);
                                    output.TemplateId = single.OrignalTemplateId;
                                    output.TemplateuniqueId = single.TemplateuniqueId;
                                    output.TemplateId = single.OrignalTemplateId;
                                    output.TagId = single.TagId;
                                    output.IsActive = true;
                                    output.LatestValue = "";
                                    templateFields.Add(output);
                                }

                            }
                            //all template clone code change
                            single.TemplateCloneCode = model.TemplateCode;

                        }
                        _context.TemplateFields.AddRange(templateFields);
                        _context.SaveChanges();
                        return Json(new { message = "Sucess", templateid = template.TemplateId });
                    }
                    else
                    {
                        var templateName = _context.Template.Count(e => e.TemplateName.ToLower().Trim() == model.TemplateName.ToLower().Trim() && e.CreatedById == userId.ToString() && e.IsDeleted == false);
                        if (templateName == 0)
                        {
                            model.CreatedById = userId.ToString();
                            model.IsActive = true;
                            Template template = new Template();
                            template.TemplateCode = model.TemplateCode;
                            template.TemplateName = model.TemplateName.Trim();
                            template.TemplateTypeId = model.TemplateTypeId;
                            template.Groups = model.Groups;
                            template.CreatedDate = model.CreatedDate;
                            template.CreatedById = model.CreatedById;
                            template.IsActive = model.IsActive;
                            template.IsDeleted = false;
                            template.CompanyId = (int)user.CompanyId;
                            //_context.Template.Add(_mapper.Map<Template>(model));
                            _context.Template.Add(template);
                            _context.SaveChanges();
                            return Json(new { message = "Sucess", templateid = template.TemplateId });
                        }
                        else
                        {
                            ViewData["TemplateNameAvailable"] = "true";
                            return Json(new { message = "Template name is already exist." });
                        }
                    }



                }
                else
                {
                    ViewData["TemplateNameAvailable"] = "true";
                    return Json(new { message = "Something went wrong please try again." });

                }
            }

            catch (Exception ex)
            {

OxyProcess/Views/Template/index.cshtml
@{
    ViewData["Title"] = "Templates";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container-fluid">
    <!-- Start Page Content -->
    <div class="row">
        <!-- Column -->

        <div class="col-lg-12">
            <div class="gp-permistion">

                <a href="@Url.Action("CreateTemplate","Template")" class="btn btn-primary btn-flat">Create New Template</a>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive edit-table m-t-40 group-tabel">


                        <table id="myTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Template Name</th>
                                    <th>Template Type</th>
                                    <th>Created Date</th>
                                    <th>Active</th>
                                    <th>Manage</th>

                                </tr>
                            </thead>

                        </table>
                    </div>


                </div>
            </div>
            <!-- Column -->

        </div>

        <!-- End PAge Content -->
    </div>
    <!-- End Container fluid  -->
    <!-- End footer -->
</div>


@section Scripts{

    
    <script type="text/javascript">
        $(document).ready(function () {     
            $.ajax({
                type: "GET",
                url: "@Url.Action("GetTemplatelist","Template")",
                "dataType": "json",
                success: function (data) {
                    datatableVariable = $('#myTable').DataTable({
                        "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                        $('td', nRow).css('background-color', 'white');
                },
                        destroy: true,
                        data: data,
                        "order": [[5, "desc"]],
                         'columnDefs': [{

                            
        'targets': [3,4], // column index (start from 0)
        'orderable': false, // set orderable false for selected columns
                        }, {

                                "targets": [5],
                                "visible": false,
                                "searchable": false
                            }],
                        columns: [
                            {
                                'data': "TemplateName",
                                'render': function (data,type,row) {
                                    return "<span class='limittext'> <a title='Manage Template'  class='' href='Template/EditTemplate/"+row['TemplateId'] +"'>"+data+"</a> </span>"


                                }
                            },


                            {
                                'data': "TemplateType.TemplateTypeName",
                                'render': function (data) {
                                    return "<span class='limittext'>" + data + "</span>"
                                }
                            },
                             
                            {
                                'data': "CreatedDate",
                                'render': function (data) {                                 
                                
                                var localTime  = moment.utc(data).toDate();
                                    localTime = moment(localTime).format('YYYY-MM-DD');
                                    return "<span class='limittext'>" + localTime+ "</span>"
                                }
                            },
                            {
                                "data": "IsActive",
                                "render": simple_checkbox
                            },
                               {
                                'data': "TemplateId",
                                "render": function (data) {
                                    return "<a title='Manage Template' data-toggle='tooltip'   class='tooltip-top fa fa-arrow-right' href='Template/EditTemplate/" + data + "'></a> / <a title='Delete' data-toggle='tooltip'  href='#' class='tooltip-top fa fa-trash-o' onclick=\'DeleteRow(" + data + ")\'></a>";


                                }
                            },

                                {
                                'data': "TemplateId",
                                
                            }
                        ],

                    });
                }
            });
        });



    </script>

    <script>


        var simple_checkbox = function (data, type, full, meta) {

            var is_checked = data == true ? "checked" : "";
              var id = full['TemplateId'];
            return '<input type="checkbox" value="'+id+'" class="checkbox disabled"' +
                is_checked + ' />';
        }



        //set initial state.
        $(document).on('change', '.checkbox', function () {
               var $this = $(this);
               var bool = $this.is(':checked');
               var id = $this.val();
               var dataToSend = {
                    'TemplateId':id,
                    'IsActive':bool
                };
               $.ajax({
                    url: '@Url.Action("ChangeTemplateActivation","Template")',
                    dataType: 'json',
                    type: "POST",
                    data: dataToSend,
                    success: function (result) {

                        if (result === "False") {
                            alert("Something Worng !");
                        }
                    },
                    error: function (result) {
                        alert("Failed");
                    }
                });
            });   
 


        function DeleteRow(id) {
         
            swal({
                title: 'Are you sure?',
                text: 'You will not be able to recover this Template!',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                closeOnConfirm: false,
                closeOnCancel: false,
                allowOutsideClick: false,

            }).then(function (dismiss) {
                if (dismiss.dismiss === 'cancel') {
                } else {
                    $.ajax({
                        type: 'POST',
                        url: "@Url.Action("DeleteTemplate", "Template")",
                        dataType: "text",
                        data: { id: id },
                    }).done(function () {
                        swal({
                            title: "Deleted",
                            text: "Template has been deleted successfully ",
                            type: "success"
                        }).then(function () {
                            location.reload(true);
                        });
                    });
                }
            });
        }
    </script>
}