OxyProcess/Models/Worker/WorkerPasswords.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OxyProcess.Models.Worker
{
    public class WorkerPasswords
    {
        [Key]
        public int Id { get; set; }
        public int WorkerId { get; set; }
        public string WorkerPassword { get; set; }

    }
}

OxyProcess/Controllers/WorkerController.cs
namespace OxyProcess.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;
    using OxyProcess.Constant;
    using OxyProcess.Data;
    using OxyProcess.Extensions;
    using OxyProcess.Helpers;
    using OxyProcess.Interface;
    using OxyProcess.Models;
    using OxyProcess.Models.AccountViewModels;
    using OxyProcess.Models.Worker;

    [Authorize]
    public class WorkerController : Controller
    {
        #region Property
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly IEmailSender _emailSender;
        public readonly ApplicationDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        #endregion

        #region Constructor
        public WorkerController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IEmailSender emailSender, IHttpContextAccessor  httpContextAcce)
        {
            _userManager = userManager;
            //    _signInManager = signInManager;
            _emailSender = emailSender;
            _context = context;
            _httpContextAccessor = httpContextAcce;
        }
        #endregion

        #region Action
        public IActionResult Index()
        {
            return View();
        }



        [HttpGet]
        public string GetAllWorker()
        {
            try
            {
                
                Int64 userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                //List<GroupsListViewModel> groups = new List<GroupsListViewModel>();
                ApplicationUser currentUser = _context.Users.Where(x => x.Id == userid).First();
                //var currentUserRole = _context.UserRoles.Where(x => x.UserId == userid).FirstOrDefault();
                //var list = _context.Users.Where(u=>u.CompanyId == currentUser.CompanyId).Join(_context.UserRoles, p => p.Id, m => m.UserId, (p, m) => new { u = p, r = m }).Where(e =>  e.r.RoleId == 3).Select(s=>s.u).OrderByDescending(e=>e.Id).ToList();
                //var list = _context.Users.Join(_context.UserRoles, p => p.Id , m => m.UserId).Where(e => e.CompanyId == currentUser.CompanyId && e.AddressId == currentUser.AddressId)



                var list = (from user in _context.Users
                            join userrole in _context.UserRoles on user.Id equals userrole.UserId
                            join wkpass in _context.WorkerPasswords on user.Id equals wkpass.WorkerId
                            where userrole.RoleId == 3 && user.CompanyId == currentUser.CompanyId
                            select new
                            {

                                FirstName = user.FirstName,
                                LastName = user.LastName,
                                Email = user.Email,
                                Suspended = user.Suspended,
                                Id = user.Id,
                              
                            }).OrderByDescending(e => e.Id).ToList();



                var json = JsonConvert.SerializeObject(list);
                return json;
            }
            catch (Exception ex)
            {
                return null;
            }

        }

        [Route("Worker/EditWorkerProfile/{uid}")]
        [HttpGet]

        public IActionResult EditWorkerProfile(string uid)
        {


            UserProfileViewModel userProfile = new UserProfileViewModel();
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                    ApplicationUser currentUser = _context.Users.Where(x => x.Id == userid).First();
                    //var currentUserRole = _context.UserRoles.Where(x => x.UserId == userid).FirstOrDefault();
                    var list = (_context.Users.Where(u => u.CompanyId == currentUser.CompanyId).Join(_context.UserRoles, p => p.Id, m => m.UserId, (p, m) => new { u = p, r = m }).Where(e => e.r.RoleId == 3).Select(s => s.u).FirstOrDefault(x => x.Id == Convert.ToInt64(uid)));
                    if (list == null)
                    {
                        return RedirectToAction("InvalidAccess", "Account");
                    }


                    if (userid > 0)
                    {
                        userProfile = (from u in _context.Users
                                       join c in _context.Companies on u.CompanyId equals c.CompanyId
                                       join a in _context.Addresses on u.AddressId equals a.AddressId
                                       join p in _context.WorkerPasswords on u.Id equals p.WorkerId
                                       where u.Id == Convert.ToInt64(uid)
                                       select new UserProfileViewModel
                                       {
                                           FirstName = u.FirstName,
                                           Email = u.Email,
                                           CompanyName = c.CompanyName,
                                           Phone = u.PhoneNumber,
                                           LastName = u.LastName,
                                           AddressLine1 = a.AddressLine1,
                                           AddressLine2 = a.AddressLine2,
                                           CountryId = a.CountryId,
                                           StateId = a.StateId,
                                           City = a.City,
                                           CountryName = a.Countries.CountryName,
                                           StateName = a.State.StateName,
                                           ZipCode = a.ZipCode,
                                       }).FirstOrDefault();






                        //Get selected Country


                        // ------- Inserting Select Item in List -------
                        //cityList.Insert(userProfile.CityId, new City { CityId = 0, CityName = "Please select city" });

                        // ------- Assigning citylist to ViewBag.ListofCategory -------




                        ViewBag.userid = uid;
                    }
                    return View(userProfile);
                }
                return RedirectToAction("Login", "Account");

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, Constants.ExMsg);
                return View(userProfile);
            }
        }




        public JsonResult EditUserProfile(EditUserSetting collection)
        {
            try
            {


                collection.value = collection.value.Trim();
                if (collection.name == "firstname")
                {
                    var user = _context.Users.FirstOrDefault(u => u.Id == collection.pk);
                    user.FirstName = collection.value;
                    _context.SaveChanges();
                    return Json(new { success = true });
                }

                if (collection.name == "lastname")
                {
                    var user = _context.Users.FirstOrDefault(u => u.Id == collection.pk);
                    user.LastName = collection.value;
                    _context.SaveChanges();
                    return Json(new { success = true });
                }

                if (collection.name == "Password")
                {
                    var user = _context.Users.FirstOrDefault(u => u.Id == collection.pk);
                    var resetToken =  _userManager.GeneratePasswordResetTokenAsync(user);
                   var passwordChangeResult =  _userManager.ResetPasswordAsync(user, resetToken.Result, collection.value);
                    if (passwordChangeResult.Result.Succeeded)
                    {
                        
                            //update worker password on worker password tbl 
                            var d = _context.WorkerPasswords.FirstOrDefault(e => e.WorkerId == user.Id);
                            d.WorkerPassword = EncryptDecryptHelper.encrypt(collection.value);
                            _context.SaveChanges();
                       

                    }
                }



                if (collection.name == "Phone")
                {
                    var user = _context.Users.FirstOrDefault(u => u.Id == collection.pk);
                    user.PhoneNumber = collection.value;
                    _context.SaveChanges();
                    return Json(new { success = true });

                }


                if (collection.name == "Email")
                {

                    try
                    {

                        var existngUser = _context.Users.Where(e => e.Email.Trim().ToLower() == collection.value.Trim().ToLower()).FirstOrDefault();
                        if (existngUser == null)
                        {
                            var user = _context.Users.FirstOrDefault(u => u.Id == collection.pk);
                            user.Email = collection.value.Trim().ToLower();
                            user.NormalizedEmail = collection.value.Trim().ToLower();
                            user.NormalizedUserName = collection.value.Trim().ToLower();
                            user.UserName = collection.value;
                            _context.SaveChanges();
                            return Json(new { success = true });

                        }
                        else
                        {
                            return Json(new { success = false, message = "Exist" });

                        }

OxyProcess/Views/Worker/CreateWorker.cshtml
@model OxyProcess.Models.AccountViewModels.RegisterViewModel

@{
    ViewData["Title"] = "Add Worker";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>

    .error{

        color:red
    }
</style>
<div class="container-fluid">
    <!-- Start Page Content -->
    <div class="row">
        <!-- Column -->

        <div class="col-lg-12">
            <div class="card card-cuss">
                <div class="card-body">
                    <div class=" row">
                        <div class="col-md-12">
                            <h2 class="heading">Add Worker</h2>
                        </div>
                    </div>
                    <form id="createEditWorker">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group col-md-4 col-sm-6 col-xs-12">
                            <label class="control-label">First Name</label>
                            <input asp-for="FirstName" type="text" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-4 col-sm-6 col-xs-12">
                            <label class="control-label">Last Name</label>
                            <input asp-for="LastName" type="text" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-4 col-sm-6 col-xs-12">
                            <label asp-for="Phone" class="control-label"></label>
                            <input asp-for="Phone" type="text" class="form-control only-number" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-4 col-sm-6 col-xs-12">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" type="email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <input id="createWorker" type="button" value="Create" class="btn btn-primary" />
                        
                            <a id="createWorker" href="@Url.Action("Index","Worker")"  class="btn btn-primary" >Back </a>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts{
    @*<script src="~/js/jquery.validate.min.js"></script>*@
<script src="~/js/lib/form-validation/jquery.validate.min.js"></script>
<script src="~/js/lib/input-Mask/inputmask.js"></script>

    <script type="text/javascript">
        $(function () {

            $("#Phone").inputmask({ "mask": "(999) 999-9999" });

            $.validator.addMethod("regxmobile", function (value, element, regexpr) {
                var d = parseInt(value.replace(/[^0-9\.]/g, ''), 10);

                return d.toString().length < 10 ? false : true;
            }, "Please enter a valid Phone.");



//            $.validator.addMethod("custom_number", function(value, element) {
//    return this.optional(element) || value === "NA" ||
//        value.match(/^[0-9,\+-]+$/);
//}, "Please enter a valid phone number");


            $('#createEditWorker').validate({
                    rules:
                    {

                        FirstName: {
                            required: true,
                            maxlength: 30
                        },
                        LastName: {
                            required: true,
                            maxlength: 30
                        },
                    Phone: {
                        
                        required: true,

                        regxmobile: 10

                    },
                        Email: { required: true },
                      message:
                        {
                            maxlength: 1024
                        }
                },
                message: {
                    FirstName: {
                        required: "Please enter first name",
                    },
                    LastName: {
                        required: "Please enter last name",
                    },
                    Phone: {
                        required: "Please enter phone number",
                    },
                    Email: {
                        required: "Please enter last email",
                    },

                },


            });



        });
    </script>

    <script type="text/javascript">
                $(document).ready(function () {



                    $('#createWorker').click(function () {




                        $(".preloader").show();
                       
                       if ($('#createEditWorker').valid()) {
                       var worker = new Object();
                       worker.FirstName = $('#FirstName').val();
                       worker.LastName = $('#LastName').val();
                       worker.Email = $('#Email').val();
                       worker.Password = randomPassword(3);
                       worker.ConfirmPassword = worker.Password;
                       worker.Phone = $('#Phone').val();
                           $.ajax({
                            url: "@Url.Action("CreateEditWorker", "Worker")",
                            dataType: "json",
                               type: "Post",
                               data: worker,
                               success: function (response) {
                                   if (response.message === 'Success') {
                                    
                                       window.location.href = '@Url.Action("Index", "Worker")';
                                   }
                                   else if (response.message === 'Error_user_exist') {
                                       $(".preloader").hide();
                                       swal({
                                           text: 'It looks like this email address is already registered.',
                                           type: 'error',
                                           confirmButtonText: 'Ok',
                                       }).then(function () {
                                         
                                       });
                                   }
                                   else {
                                       $(".preloader").hide();
                                       swal({
                                           text: 'fail to create worker',
                                           type: 'error',
                                           confirmButtonText: 'Ok',
                                       }).then(function () {
                                           location.reload(true);
                                       });

                                   }
                               },
                               error: function () {
                                 $(".preloader").hide();
                                alert("Error in Ajax");
                                location.reload(true);
                            }

                        });
                        }
                    else
                        {

                              $(".preloader").hide();

                        }
                    });
               });

               function randomPassword(length) {
                var char1 = "abcdefghijklmnopqrstuvwxyz";
                var char2 = "&&";
                var char3 = "1234567890";
                var char4 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
                var pass = "";
                   for (var x = 0; x < length; x++) {
                       
                    var i = Math.floor(Math.random() * char1.length);
                    pass += char1.charAt(i);
                    }

                    for (var x = 0; x < length; x++) {
                        var i = Math.floor(Math.random() * char2.length);
                        pass += char2.charAt(i);
                    }

                    for (var x = 0; x < length; x++) {
                        var i = Math.floor(Math.random() * char3.length);
                        pass += char3.charAt(i);
                   }
                   for (var x = 0; x < length; x++) {
                       var i = Math.floor(Math.random() * char4.length);
                       pass += char4.charAt(i);
                   }

            return pass;
        }
            </script>

}

OxyProcess/Views/Worker/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <!-- Start Page Content -->
    <div class="row">
        <!-- Column -->

        <div class="col-lg-12">
            <div class="gp-permistion">
                <a href="@Url.Action("CreateWorker","Worker")" class="btn btn-primary btn-flat">Add Worker</a>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive edit-table m-t-40 group-tabel">


                        <table id="myTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>FirstName</th>
                                    <th>LastName</th>
                                    <th>UserName</th>
                                    <th>Is suspended</th>
                                   
                                    
                                    <th>Manage</th>
                                </tr>
                            </thead>

                        </table>
                    </div>


                </div>
            </div>
            <!-- Column -->

        </div>

        <!-- End PAge Content -->
    </div>
    <!-- End Container fluid  -->
    <!-- End footer -->
</div>
@section Scripts{
    <script src="~/js/lib/datatables/datatables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $.ajax({
                type: "GET",
                url: "@Url.Action("GetAllWorker", "Worker")",
                "dataType": "json",
                success: function (data) {
                    datatableVariable = $('#myTable').DataTable({
                         "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                        $('td', nRow).css('background-color', 'white');
                },
                        destroy: true,
                        data: data,
                        "order": [[5, "desc"]],

                         'columnDefs': [{


        'targets': [4], // column index (start from 0)
        'orderable': false, // set orderable false for selected columns
                        }, {

                                "targets": [5],
                                "visible": false,
                                "searchable": false
                            },


                        ],
                        columns: [
                            {
                                'data': "FirstName",
                                'render': function (data) {

                                    return "<span class='limittext'>" + data + "</span>"

                                }
                            },
                            {
                                'data': "LastName",
                                'render': function (data) {

                                    return "<span class='limittext'>" + data + "</span>"
                                }
                            },
                            {
                                'data': "Email",
                                'render': function (data) {

                                    return "<span class='limittext'>" + data + "</span>"
                                }
                            },

                            {
                                'data': "Suspended",
                                "render": simple_checkbox
                            },

                           
                            {
                                'data': "Id",
                                "render": function (data) {
                                    return "<a title='Manage Worker' data-toggle='tooltip'   class='tooltip-top fa fa-arrow-right' href='Worker/EditWorkerProfile/" + data + "'></a> ";
                                }
                            },
                            {
                                'data': "Id",

                            }
                        ],
                        //"fnDrawCallback": function () {
                        //    jQuery('#myTable #kv-toggle-demo').bootstrapToggle();
                        //}
                    });
                }
            });

        });
    </script>
    <script type="text/javascript">
        var simple_checkbox = function (data, type, full, meta) {

            var is_checked = data == true ? "checked" : "";
            var id = full['Id'];
            return '<input type="checkbox" value="' + id + '" class="checkbox disabled"' +
                is_checked + ' />';
        }







        //set initial state.
        $(document).on('change', '.checkbox ', function () {
            var $this = $(this);
            var bools = $this.is(':checked');
            var task = "Suspend";
            if (bools === false) {

                task = "you sure you want to cancel suspension";
            }
            else {

                task = " you want Suspend this worker!";
            }
            swal({
                title: 'Are you sure?',
                text: task,
                type: 'warning',
                showCancelButton: true,
                 allowOutsideClick: false,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes',
                closeOnConfirm: false,
                closeOnCancel: false

            }).then(function (dismiss) {
                if (dismiss.dismiss === 'cancel') {

                     var bool = $this.is(':checked');
                    var id = $this.val();
                    if (bool === true) {
                        $this.prop('checked', false);
                    }
                    else {

                        $this.prop('checked', true);
                    }
                } else {

                    var bool = $this.is(':checked');
                    var id = $this.val();
                    var dataToSend = {
                        'Id': id,

                    };
                    $.ajax({
                        url: '@Url.Action("ChangeWorkerSuspendedStatus","Worker")',
                        dataType: 'json',
                        type: "POST",
                        data: { user: dataToSend, change: bool },
                        success: function (result) {

                            if (result === "False") {
                                alert("Something Worng !");
                            }
                        },
                        error: function (result) {
                            alert("Failed");
                        }
                    });
                }
            });
            });

    </script>
}