OxyProcess/Controllers/AccessRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OxyProcess.Data;
using OxyProcess.Models.SpecialPermission;

namespace OxyProcess.Controllers
{
    public class AccessRequestController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AccessRequestController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AccessRequest
        public ActionResult Index()
        {
            return View();
        }

        //GET: Pending Request
        public ActionResult PendingRequest()
        {
            return View();
        }


        //GET: Pending Request List
        [HttpGet]
        public ActionResult PendingRequestList()
        {
            try {


                int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var user = _context.Users.FirstOrDefault(e => e.Id == userid);
                var AccessReq = _context.SpecialPermission.Where(e => e.Requested_User == user.Id).ToList();

                IQueryable data = (from u in _context.Users
                                join accreq in AccessReq on u.Id equals accreq.Requested_User
                                join tegintemp in _context.TaginsideTemplates on accreq.Unique_Template_Id equals tegintemp.TemplateuniqueId
                                join tag in _context.Tag on tegintemp.TagId equals tag.Id
                                join temp in _context.Template on tegintemp.OrignalTemplateId equals temp.TemplateId
                                select new RequestPersonViewModel
                                {
                                    Id = accreq.Id,
                                    AccessPermission = accreq.AccessGranted,
                                    Tag = tag.TagNumber,
                                    Reject = accreq.Rejected,
                                    TemplateName = temp.TemplateName

                                }).Distinct();


                return Json(new { Sucesss = false, Data = data });
            }
            catch
            {
                return Json(new { Sucesss = false, Data ="" }) ;

            }
        }

        // Post: AccessRequest/RejectRequest/5
        [HttpPost]
        public ActionResult RejectRequest(int Id)
        {
            try
            {
                int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                if (userid != 0)
                {
                    var request = _context.SpecialPermission.FirstOrDefault(e => e.Id == Id);
                    request.Rejected = true;
                    _context.SaveChanges();
                    return Json(new { Success = true});
                }
                return Json(new { Success = false });
            }
            catch
            {
                return Json(new { Success = false });
            }
        }

        public JsonResult GetAllRequest()
        {
            try
            {
                int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var user = _context.Users.FirstOrDefault(e => e.Id == userid);
                var AccessReq = _context.SpecialPermission.Where(e => e.Company_Id == user.CompanyId && e.Rejected == false).ToList();

                IQueryable data = (from u in _context.Users
                                join accreq in AccessReq on u.Id equals accreq.Requested_User
                                join tegintemp in _context.TaginsideTemplates on accreq.Unique_Template_Id equals tegintemp.TemplateuniqueId
                                join tag in _context.Tag on tegintemp.TagId equals tag.Id
                                join temp in _context.Template on tegintemp.OrignalTemplateId equals temp.TemplateId
                                select new RequestPersonViewModel
                                {
                                    Id = accreq.Id,
                                    FullName = u.LastName + " " + u.LastName,
                                    AccessPermission = accreq.AccessGranted,
                                    UserName = u.Email,
                                    Tag = tag.TagNumber,
                                    TemplateName = temp.TemplateName

                                }).Distinct();

                return Json(data);
            }
            catch
            {
                return Json("False");


            }
        }


        [HttpPost]
        public JsonResult ChangePermission(int Id, bool change)
        {

            try
            {
                int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);

                var user = _context.Users.FirstOrDefault(e => e.Id == userid);
                var AccessReq = _context.SpecialPermission.FirstOrDefault(e => e.Company_Id == user.CompanyId && e.Id == Id);

                if (AccessReq != null)
                {
                    AccessReq.AccessGranted = change;
                    _context.SaveChanges();
                    return Json("True");

                }
                return Json("False");

            }

            catch (Exception ex)
            {
                return Json("False");
            }

        }

    }
}

OxyProcess/Controllers/GroupController.cs
namespace OxyProcess.Controllers
{
    using System;
    using System.Linq;
    using System.Security.Claims;
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Newtonsoft.Json;
    using OxyProcess.Data;
    using OxyProcess.Models;
    using OxyProcess.Models.Group;
    using OxyProcess.Models.GroupsViewModels;
    using OxyProcess.Constant;
    using Microsoft.AspNetCore.Authorization;

    [Route("[controller]/[action]")]
    [Authorize(Roles = "Admin")]
    public class GroupController : Controller
    {
        #region Property
        public readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        //private readonly IMapper _mapper;
        #endregion

        #region Constructor
        public GroupController(ApplicationDbContext context, UserManager<ApplicationUser> userManager/* IMapper mapper*/)
        {
            _context = context;
            _userManager = userManager;
            //_mapper = mapper;
        }
        #endregion

        [HttpGet]
        [AllowAnonymous]
        public JsonResult GroupsMembers(string term)
        {
            try
            {

                int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var user = _context.Users.FirstOrDefault(e => e.Id == userid);
                var list = _context.Users.Join(_context.UserRoles, p => p.Id, m => m.UserId, (p, m) => new { u = p, r = m }).Where(e => e.r.RoleId == 3 && e.u.CompanyId == user.CompanyId || e.r.RoleId == 4).Select(s => s.u).OrderByDescending(e => e.Id).ToList();
                var UserList = (from N in list
                                where N.Email.ToLower().StartsWith(term.ToLower())
                                select new { N.Email });
                return Json(UserList);
            }
            catch (Exception)
            {
                return Json(null);
            }
        }


        #region Action
        //Index of group

        public ActionResult Index()
        {
            //if (TempData["Message"] != null)
            //{
            //    ViewBag.Msg = TempData["Message"];
            //}
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddGroup(AddGroupViewModel model)
        {
            //transaction method for prevent ghost Data.
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        /// check name charector is not more then 32 words
                        if (model.GroupName.Length >= 32)
                        {
                            ModelState.AddModelError(string.Empty, "Group name is too long.");
                            return View("Index", model);
                        }

                        model.GroupName = model.GroupName.Trim();

                        int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                        var groups = _context.Groups.Where(x => x.GroupName.ToLower() == model.GroupName.ToLower() && x.CreatedById == userid.ToString()).ToList().Count();
                        if (groups == 0)
                        {
                            Groups group = new Groups
                            {
                                GroupName = model.GroupName,
                                CreatedDate = DateTime.Now,
                                CreatedById = User.FindFirst(ClaimTypes.NameIdentifier).Value,

                            };

                            _context.Groups.Add(group);
                            _context.SaveChanges();
                            var groupid = group.GroupId;
                            GroupPermission gp = new GroupPermission()
                            {
                                GroupId = groupid,
                                None = true
                            };
                            _context.GroupPermission.Add(gp);
                            _context.SaveChanges();
                            TempData.Remove("Message");
                            TempData.Add("Message", "Group Added Successfully");
                            //return RedirectToAction("AddGroup");
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, "Group already exists please enter different group name.");


                            return View("Index", model);
                        }

                    }

                    transaction.Commit();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                }
            }
            return RedirectToAction("Index");
        }



        /// <summary>
        /// Get all group list
        /// </summary>
        [HttpGet]
        public string GetAllGroups()
        {
            try
            {
                int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                //List<GroupsListViewModel> groups = new List<GroupsListViewModel>();
                var list = _context.Groups.Where(e => e.CreatedById == userid.ToString()).OrderByDescending(e => e.GroupId).OrderByDescending(e => e.GroupId).ToList();
                var json = JsonConvert.SerializeObject(list);
                return json;
            }
            catch (Exception ex)
            {
                return null;
            }

        }
        #endregion


        /// <summary>
        /// Edit group information
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

        #region EditGroupMemberPermission
        //[HttpPost]
        //[HttpGet]
        public IActionResult Edit(int id)
        {
            var groupName = _context.Groups.Where(e => e.GroupId == id).FirstOrDefault();
            int userid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);

            if (groupName == null)
            {
                return RedirectToAction("InvalidAccess", "Account");
            }

            if (groupName.CreatedById != userid.ToString())
            {
                return RedirectToAction("InvalidAccess", "Account");
            }

            var grouppermission = _context.GroupPermission.Where(x => x.GroupId == id).FirstOrDefault();
            var model = new GroupMemberPermissionModel();
            model.addMemberToGroupViewModel = new AddMemberToGroupViewModel();
            model.groupPermissionViewModel = new GroupPermissionViewModel();
            model.addMemberToGroupViewModel.GroupId = id;
            model.groupPermissionViewModel.GroupId = id;
            model.GroupName = groupName.GroupName;



            if (grouppermission != null)
            {
                model.groupPermissionViewModel.Read = grouppermission.Read;
                model.groupPermissionViewModel.Write = grouppermission.Write;
                model.groupPermissionViewModel.Edit = grouppermission.Edit;
                model.groupPermissionViewModel.Delete = grouppermission.Delete;
                model.groupPermissionViewModel.None = grouppermission.None;
            }
            //if (TempData["Message"] != null)
            //{
            //    ViewBag.Msg = TempData["Message"];
            //    TempData["Message"] = null;
            //}
            return View(model);
        }

        /// <summary>
        /// Add member to the particular group
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult AddMemberToGroup(GroupMemberPermissionModel model)
        //{
        //    try
        //    {

        //        if (ModelState.IsValid)
        //        {
        //            var user = _userManager.FindByEmailAsync(model.addMemberToGroupViewModel.Email).Result;
        //            model.GroupName = _context.Groups.Where(e => e.GroupId == model.addMemberToGroupViewModel.GroupId).Select(g => g.GroupName).FirstOrDefault();
        //            if (user == null)
        //            {
        //                //ModelState.AddModelError(string.Empty, "User not Found ");
        //                //return View("Edit", model);
        //                ViewData["NotFound"] = "true";
        //                return View("Edit", model);
        //            }
        //            else
        //            {
        //                var grpmember = _context.GroupMembers.ToList().Where(x => x.UserId == user.Id && x.GroupId == model.addMemberToGroupViewModel.GroupId).Count();
        //                if (grpmember == 0)
        //                {
        //                    GroupMembers group = new GroupMembers
        //                    {
        //                        GroupId = model.addMemberToGroupViewModel.GroupId,
        //                        UserId = user.Id,
        //                    };
        //                    _context.GroupMembers.Add(group);
        //                    _context.SaveChanges();
        //                    TempData.Add("Message", "Group Member Added Successfully");
        //                    return RedirectToAction("Edit", new { Id = model.addMemberToGroupViewModel.GroupId });
        //                }
        //                else
        //                {
        //                    //ModelState.AddModelError(string.Empty, "User Already Available");
        //                    //return View("Edit", model);

OxyProcess/ViewComponents/HeaderUserDetailsViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OxyProcess.Data;
using OxyProcess.Models;
using OxyProcess.Models.AccountViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using System.Security.Principal;
using Microsoft.AspNetCore.Routing;
using System.Threading.Tasks;

namespace OxyProcess.ViewComponents
{
    public class HeaderUserDetailsViewComponent : ViewComponent
    {
        public readonly ApplicationDbContext _context;
  
        public readonly SignInManager<ApplicationUser> SignInManager;
      
        public HeaderUserDetailsViewComponent(ApplicationDbContext app, SignInManager<ApplicationUser> sig)
        {

            _context = app;
            SignInManager = sig;
          

        }

        public  IViewComponentResult Invoke(int numberOfItems)
        {
            try
            {
                int userid = Convert.ToInt32(UserClaimsPrincipal.FindFirst(ClaimTypes.NameIdentifier).Value);
                var user = _context.Users.FirstOrDefault(u => u.Id == userid);


               ApplicationUser userProfile = new ApplicationUser();

                
                if (userid > 0)
                {
                   var  userProfiles =   (from u in _context.Users
                                   join c in _context.Companies on u.CompanyId equals c.CompanyId
                                   where u.Id == userid
                                   select  new  ApplicationUser
                                   {
                                       FirstName = u.FirstName,
                                       LastName = u.LastName,
                                       CompanyName = c.CompanyName,

                                   }).FirstOrDefault();
                }
                //return  View("HeaderUserDetails", userProfile);
                return View("HeaderUserDetails", userProfile);
            }
            catch (Exception ex)
            {

                throw;
            }

          
          

        }
    }
}

OxyProcess/Views/Shared/InvalidAccess.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">Page not found or you have no Permission to access this.</h2>

OxyProcess/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@using Microsoft.AspNetCore.Rewrite.Internal.UrlActions
@using Microsoft.AspNetCore.Mvc
@using System;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon.png">
    <title>OxyProces | @ViewData["Title"]</title>


    <environment include="Development">
        <link href="~/css/lib/bootstrap/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="~/css/helper.css" rel="stylesheet">
        <link href="~/css/style.css" rel="stylesheet">
        <link href="~/css/lib/sweetalert/sweetalert2.min.css" rel="stylesheet" />
        <link href="~/css/lib/chosen/chosen.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="~/css/lib/bootstrap/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="~/css/helper.css" rel="stylesheet">
        <link href="~/css/style.css" rel="stylesheet">
        <link href="~/css/lib/sweetalert/sweetalert2.min.css" rel="stylesheet" />
        <link href="~/css/lib/chosen/chosen.css" rel="stylesheet" />
        
    </environment>
    @RenderSection("Styles", required: false)
</head>
<body class="fix-header fix-sidebar">
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- Main wrapper  -->
    <div id="main-wrapper">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        @(await Component.InvokeAsync("HeaderUserDetails"))

                    }
                    else
                    {
                        string authfail = Url.Action("Login", "Account");
                        Context.Response.Redirect(authfail);
                    }
        <!-- End header header -->
        <!-- Left Sidebar  -->
        <div class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <ul id="sidebarnav">

                    @*<li class="nav-label">Manu </li>*@

                    <li>
                        <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" onclick="window.location = '@Url.Action("Index","Home")';" style="width: 100%;">
                            Home
                        </button>
                    </li>
                    @if (this.User.IsInRole("Admin"))
                    {
                        <li>
                            <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" onclick="window.location = '@Url.Action("Index","Template")';" style="width: 100%;">
                                Form Template
                            </button>
                        </li>
                        <li>
                            <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" onclick="window.location = '@Url.Action("Index","FormTag")';" style="width: 100%;">
                                Tag
                            </button>

                        </li>
                        <li>
                            <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" onclick="window.location = '@Url.Action("Index","Group")';" style="width: 100%;">
                                Groups
                            </button>
                        </li>
                        <li>
                            <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" onclick="window.location = '@Url.Action("Index","Worker")';" style="width: 100%;">
                                Workers
                            </button>
                        </li>

                        @*<li>
                            <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" onclick="window.location = '@Url.Action("Index","AccessRequest")';" style="width: 100%;">
                                Access Request
                            </button>
                        </li>*@
                    }
                    else if (this.User.IsInRole("Worker"))
                    {
                        <li>
                            <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" onclick="window.location = '@Url.Action("Index","FormTag")';" style="width: 100%;">
                                Tag
                            </button>

                        </li>
                        @*<li>
                <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" onclick="window.location = '@Url.Action("Index","FormTag")';" style="width: 100%;">
                    Create Tag
                </button>
            </li>*@
                    }

                    @*<li>
                        <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" onclick="window.location = '@Url.Action("PendingRequest","AccessRequest")';" style="width: 100%;">
                            Pending Request
                        </button>

                    </li>*@
                    
                    <li>
                        <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" onclick="window.location = '@Url.Action("Index","UserSetting")';" style="width: 100%;">
                            Settings
                        </button>
                    </li>

                </ul>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </div>
        <!-- End Left Sidebar  -->
        <!-- Page wrapper  -->
        <div class="page-wrapper">
            @RenderBody()            
        </div>
        <!-- End Page wrapper  -->
    </div>
    <environment include="Development">
        <script src="~/js/lib/jquery/jquery.min.js"></script>
        <!-- Bootstrap tether Core JavaScript -->
        <script src="~/js/lib/bootstrap/js/popper.min.js"></script>
        <script src="~/js/lib/bootstrap/js/bootstrap.min.js"></script>
        <!-- slimscrollbar scrollbar JavaScript -->
        <script src="~/js/jquery.slimscroll.js"></script>
        <!--Menu sidebar -->
        <script src="~/js/sidebarmenu.js"></script>
        <!--stickey kit -->
        <!--Custom JavaScript -->
        <script src="~/js/custom.min.js"></script>
        <script src="~/js/sweetalert2.all.min.js"></script>
        <script src="~/js/jquery.validate.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.min.js"></script>
        <script src="~/js/lib/chosen/Chosen.js"></script>
        <script src="~/js/lib/datatables/datatables.min.js"></script>
        <script type="text/javascript">
            $('body').tooltip({ selector: '[data-toggle="tooltip"]' });
            $('.only-number').bind('keyup paste', function () {
                this.value = this.value.replace(/[^0-9]/g, '');
            });
        </script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/lib/jquery/jquery.min.js"></script>
        <!-- Bootstrap tether Core JavaScript -->
        <script src="~/js/lib/bootstrap/js/popper.min.js"></script>
        <script src="~/js/lib/bootstrap/js/bootstrap.min.js"></script>
        <!-- slimscrollbar scrollbar JavaScript -->
        <script src="~/js/jquery.slimscroll.js"></script>
        <!--Menu sidebar -->
        <script src="~/js/sidebarmenu.js"></script>
        <!--stickey kit -->
        <!--Custom JavaScript -->
        <script src="~/js/custom.min.js"></script>
        <script src="~/js/sweetalert2.all.min.js"></script>
        <script src="~/js/jquery.validate.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.min.js"></script>
        <script src="~/js/lib/chosen/Chosen.js"></script>
        <script src="~/js/lib/datatables/datatables.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    
</body>
</html>