OxyProcess/Controllers/FormTagController.cs
namespace OxyProcess.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.FileProviders;
    using Newtonsoft.Json;
    using OxyProcess.Constant;
    using OxyProcess.Data;
    using OxyProcess.Models.FormTag;
    using OxyProcess.Models.Template;
    using OxyProcess.ViewModels.FormTag;
    using AutoMapper;
    using OxyProcess.Helpers;
    using OxyProcess.Models.SpecialPermission;
    using System.Runtime.CompilerServices;

    public class FormTagController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;
        private readonly IHostingEnvironment _env;
        public FormTagController(ApplicationDbContext _ApplicationDbContext, IMapper mapper, IHostingEnvironment env)
        {
            _env = env;
            _mapper = mapper;
            _context = _ApplicationDbContext;
        }

        [Authorize(Roles = "Admin,Worker")]
        public IActionResult Index()
        {
            return View("CreateTag");
        }

        [Authorize(Roles = "Admin,Worker")]
        public IActionResult FindTagId()
        {
            return View("FindTagId");
        }

      

        /// <summary>
        /// Tag Search Result
        /// </summary>
        /// <param name="SearchTag"></param>
        /// <returns>Tag Forms</returns>
        [HttpGet]
        public IActionResult TagSearchResult(string SearchTag)
        {
            try
            {
                var tag = _context.Tag.FirstOrDefault(e => e.TagNumber == SearchTag);

                if (tag == null)
                {

                    TempData["TagErrorMessage"] = "Tag not found";
                    return RedirectToAction("Index", "Home");

                }


                return View(tag);
            }
            catch
            {

                return View();
            }
        }

        /// <summary>
        /// Get Fill Form Data
        /// </summary>
        /// <param name="Templateid"></param>
        /// <returns>ID Of Template</returns>

        [HttpGet]
        public ActionResult FillFormData(int TemplateUniqueId, string returnSearchTag, int DataEntryID)
        {
            try
            {


                var Template = (from taginsideTemplates in _context.TaginsideTemplates
                                join
                              template in _context.Template on taginsideTemplates.OrignalTemplateId equals template.TemplateId
                                where taginsideTemplates.TemplateuniqueId == TemplateUniqueId
                                select template).FirstOrDefault();

                var TemplateType = Template.TemplateTypeId;



                if (TemplateType == 1) //if template is reguler to redirect multipal entry page
                    {
                  
                        return RedirectToAction("RegulerFormEntries", new { formUniqueId = TemplateUniqueId, returnSearchTag = returnSearchTag });

                    }
                    var TagFormDataEntry = _context.TagFormDataEntry.FirstOrDefault(e => e.TemplateuniqueId == TemplateUniqueId);


                    if (TagFormDataEntry == null)
                    {

                    CheckUserRightsHelper checkUserRightsHelper = new CheckUserRightsHelper(_context);
                    int Currentuserid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);

                    var userRights = checkUserRightsHelper.CheckUserAcceess(Template.TemplateId, Currentuserid);
                    //if user has no permission for view 
                    if (userRights.Write == false)
                    {
                        return RedirectToAction("TagReportCardList", new { SearchTag = returnSearchTag });
                        //user has nop permission logic
                    }

                        TaginsidTemplatesViewModel TaginsideTemplatesData = new TaginsidTemplatesViewModel();
                        TaginsideTemplatesData.TemplateuniqueId = TemplateUniqueId;
                        TaginsideTemplatesData.TagNumber = returnSearchTag;
                        return View(TaginsideTemplatesData);
                    }

                    else
                    {

                        return RedirectToAction("ViewEditFormData", new { TemplateUniqueId = TemplateUniqueId, returnSearchTag = returnSearchTag, DataEntryID = TagFormDataEntry.Id });

                    }
               
            }
            catch (Exception ex)
            {
                return View(ex);
            }

        }


        [HttpGet]
        public ActionResult NewFormDataForReguler(int TemplateUniqueId, string returnSearchTag)
        {
            try
            {

                int OrignalTemplateId = _context.TaginsideTemplates.FirstOrDefault(e => e.TemplateuniqueId == TemplateUniqueId).OrignalTemplateId;
                int Currentuserid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);

                CheckUserRightsHelper checkUserRightsHelper = new CheckUserRightsHelper(_context);

                var userRights = checkUserRightsHelper.CheckUserAcceess(OrignalTemplateId, Currentuserid);

                if(userRights.Write == true)
                {


            
                var TagFormDataEntry = _context.TagFormDataEntry.FirstOrDefault(e => e.TemplateuniqueId == TemplateUniqueId);
                var TemplateType = (from taginsideTemplates in _context.TaginsideTemplates
                                    join
                                  template in _context.Template on taginsideTemplates.OrignalTemplateId equals template.TemplateId
                                    where taginsideTemplates.TemplateuniqueId == TemplateUniqueId
                                    select template).Select(e => e.TemplateTypeId).FirstOrDefault();


                if (TemplateType == 1) //  if reguler form then  create new form every time. 
                {
                    TaginsidTemplatesViewModel TaginsideTemplatesData = new TaginsidTemplatesViewModel();
                    TaginsideTemplatesData.TemplateuniqueId = TemplateUniqueId;
                    TaginsideTemplatesData.TagNumber = returnSearchTag;
                    return View("FillFormData", TaginsideTemplatesData);

                }

                else
                {
                    return View();

                }


                }
                else{

                    return RedirectToAction("Index","Home");
                }


            }
            catch (Exception ex)
            {
                return View(ex);
            }

        }


        [HttpGet]
        public ActionResult EditViewFormDataForReguler(int TemplateUniqueId, string returnSearchTag, int DataEntryId)
        {
            try
            {


                return RedirectToAction("ViewEditFormData", new { TemplateUniqueId = TemplateUniqueId, returnSearchTag = returnSearchTag, DataEntryId = DataEntryId });

            }
            catch (Exception ex)
            {
                return View(ex);
            }

        }

        /// <summary>
        /// Get New Form Field Data
        /// </summary>
        /// <param name="SearchTag"></param>
        /// <returns>Tag inside Templates</returns>
        [HttpGet]
        public JsonResult GetNewFormFieldData(int TemplateuniqueId)
        {
            try
            {
                var data = _context.TaginsideTemplates.FirstOrDefault(e => e.TemplateuniqueId == TemplateuniqueId);
                var Tag = _context.Tag.FirstOrDefault(e => e.Id == data.TagId);
                var TagList = TagJsonToListConvert(Tag.TagCode);
                var Templatename = TagList.FirstOrDefault(e => e.uniqid == data.TemplateuniqueId).secondname;

                var taginsidTemplatesViewModel = _mapper.Map<TaginsidTemplatesViewModel>(data);
                taginsidTemplatesViewModel.TemplateName = Templatename;
                taginsidTemplatesViewModel.TagNumber = Tag.TagNumber;
                return Json(taginsidTemplatesViewModel);

            }
            catch (Exception ex)
            {
                return Json("");

            }
        }



        /// <summary>
        /// Tag Report Card List
        /// </summary>
        /// <param name="SearchTag"></param>
        /// <returns>Tag Forms</returns>
        [HttpGet]
        [Route("FormTag/SearchTag")]
        public IActionResult TagReportCardList(string SearchTag)
        {
            try
            {
                var tag = _context.Tag.FirstOrDefault(e => e.TagNumber == SearchTag);

                if (tag == null)
                {

                    TempData["TagErrorMessage"] = "Tag not found";
                    return RedirectToAction("Index", "Home");

                }


                return View(tag);
            }
            catch
            {

                return View();
            }
        }

        [HttpGet]
        public ActionResult EditFormData(int TemplateUniqueId, string returnSearchTag)
        {
            try
            {

                int Currentuserid = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                bool UserHasPermission = false;
                var tagDetails = _context.TaginsideTemplates.FirstOrDefault(x => x.TemplateuniqueId == TemplateUniqueId);
                if (tagDetails != null)
                {
                    var TemplateDetails = _context.Template.FirstOrDefault(t => t.TemplateId == tagDetails.OrignalTemplateId);
                    if (TemplateDetails != null)
                    {

                        if (TemplateDetails.Groups == "0")

OxyProcess/Controllers/HomeController.cs
namespace OxyProcess.Controllers
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using OxyProcess.Models;
    using System.Diagnostics;
    using System.Security.Claims;

    public class HomeController : Controller
    {
        #region Property
        private readonly UserManager<ApplicationUser> _userManager;
        #endregion

        #region Constructor
        public HomeController(UserManager<ApplicationUser> um)
        {
            _userManager = um;
        }
        #endregion

        #region Action
        public IActionResult Index()
        {
           
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult UnderConstruction()
        {
            return View();
        }
        #endregion

    }
}

OxyProcess/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!-- Container fluid  -->
<div class="container-fluid">
    <!-- Start Page Content -->
    <div class="row">
        <!-- Column -->
        <div class="col-lg-12">



            <div class="card">
                <div class="card-body">
                    <div class=" row">
                        <div class="col-md-12">
                            <div class="search-d">
                                @*@using (Html.BeginForm("TagSearchResult", "FormTag", FormMethod.Get))
                                    {
                                        <div class="input-group input-group-default">
                                            <span class="input-group-btn"><button class="btn btn-primary" type="submit"><i class="ti-search"></i></button></span>
                                            <input placeholder="Search Tag Number" id="SearchTag" name="SearchTag" type="text" maxlength="17" class="form-control" required>
                                        </div>

                                    }*@

                                @using (Html.BeginForm("TagReportCardList", "FormTag", FormMethod.Get))
                                {
                                    <div class="input-group input-group-default">
                                        <span class="input-group-btn"><button class="btn btn-primary" type="submit"><i class="ti-search"></i></button></span>
                                        <input placeholder="Enter Tag Number" id="SearchTag" name="SearchTag" type="text" maxlength="17" class="form-control" required>
                                    </div>

                                }
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>
@section Scripts{

    @if (TempData["TagErrorMessage"] != null)
    {
        @*<div class="alert alert-danger"> Tag not found. <a class="pull-right" style="cursor:pointer;" data-dismiss="alert">x</a> </div>*@
        <script>
                swal({
                    text: 'Tag Not Found.',
                    type: 'error',
                    confirmButtonText: 'Ok',
                }).then(function () {

                });


        </script>
    }


    <script type="text/javascript">
        $(function () {
            $('[id*=SearchTag]').on('keypress', function () {
                var number = $(this).val();
                if (number.length == 2) {
                    $(this).val($(this).val() + '-');
                }
                else if (number.length == 7) {
                    $(this).val($(this).val() + '-');
                }

                else if (number.length == 7) {
                    $(this).val($(this).val() + '-');
                }

                else if (number.length == 12) {
                    $(this).val($(this).val() + '-');
                }
            });
        });

         



    </script>
}

OxyProcess/Views/Home/UnderConstruction.cshtml
@{
    ViewData["Title"] = "UnderConstruction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>UnderConstruction</h1>